services:
  postgres:
    image: postgres:15
    container_name: MercaPostgres
    environment:
      POSTGRES_USER: merca
      POSTGRES_PASSWORD: recife123
      POSTGRES_DB: merca-recife
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
