CREATE TABLE tb_box
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    market_id BIGINT                                  NOT NULL,
    image     BYTEA,
    CONSTRAINT pk_tb_box PRIMARY KEY (id)
);