CREATE TABLE tb_market
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_tb_market PRIMARY KEY (id)
);

CREATE TABLE tb_market_boxes
(
    box_id    BIGINT NOT NULL,
    market_id BIGINT NOT NULL
);

ALTER TABLE tb_market_boxes
    ADD CONSTRAINT unq_market_box UNIQUE (market_id, box_id);

ALTER TABLE tb_market_boxes
    ADD CONSTRAINT fk_tbmarbox_on_box FOREIGN KEY (box_id) REFERENCES tb_box (id);

ALTER TABLE tb_market_boxes
    ADD CONSTRAINT fk_tbmarbox_on_market FOREIGN KEY (market_id) REFERENCES tb_market (id);

ALTER TABLE tb_box
    ADD CONSTRAINT FK_TB_BOX_ON_MARKET FOREIGN KEY (market_id) REFERENCES tb_market (id);