CREATE TABLE tb_mechant_boxes
(
    box_id      BIGINT NOT NULL,
    merchant_id BIGINT NOT NULL
);

CREATE TABLE tb_merchant
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    cpf      VARCHAR(255),
    email    VARCHAR(255),
    contact  VARCHAR(255),
    approved BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tb_merchant PRIMARY KEY (id)
);

ALTER TABLE tb_mechant_boxes
    ADD CONSTRAINT unq_merchant_box UNIQUE (merchant_id, box_id);

ALTER TABLE tb_mechant_boxes
    ADD CONSTRAINT fk_tbmecbox_on_box FOREIGN KEY (box_id) REFERENCES tb_box (id);

ALTER TABLE tb_mechant_boxes
    ADD CONSTRAINT fk_tbmecbox_on_merchant FOREIGN KEY (merchant_id) REFERENCES tb_merchant (id);